"""
Executive Threat Report Generator - HTML and Markdown formats.

Generates professional CISO / Red Team Threat Intelligence reports with executive
summaries, vulnerability breakdowns, asset inventories, attack path analysis, and
actionable remediation roadmaps.
"""

from __future__ import annotations

import datetime
from typing import Any, Dict, List, Optional

from heimdall.core.copilot import ThreatCopilot
from heimdall.core.models import EntityType, GraphEdge, GraphNode
from heimdall.graph.clustering import GraphClusterEngine


class ExecutiveReportGenerator:
    """Generates high-fidelity executive security reports in HTML and Markdown."""

    def __init__(self) -> None:
        self.copilot = ThreatCopilot()
        self.cluster_engine = GraphClusterEngine()

    def generate_markdown(
        self,
        target_name: str,
        nodes: List[GraphNode],
        edges: List[GraphEdge],
        attack_paths: Optional[List[Dict[str, Any]]] = None,
    ) -> str:
        """Generate executive threat assessment in GitHub-flavored Markdown."""
        now = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
        briefing = self.copilot.generate_executive_briefing(nodes, edges, attack_paths)
        clusters = self.cluster_engine.detect_communities(nodes, edges)

        md = []
        md.append(f"# Executive Threat Intelligence Assessment: {target_name}\n")
        md.append(f"**Generated by:** Heimdall OSINT Threat Engine  ")
        md.append(f"**Date:** {now}  ")
        md.append(f"**Overall Posture Rating:** `{briefing['posture_rating']}`\n")

        md.append("## 1. Executive Summary\n")
        md.append(
            f"Heimdall completed autonomous link analysis on **{briefing['total_assets']} infrastructure assets** "
            f"across **{len(edges)} relational linkages**. "
            f"Based on real-time DNS correlation, cloud storage enumeration, exposure probing, and attack-path graphing, "
            f"the current attack surface threat posture is evaluated as **{briefing['posture_rating']}**.\n"
        )

        md.append("### Key Attack Surface Metrics\n")
        md.append("| Metric | Count |")
        md.append("| :--- | :--- |")
        md.append(f"| Total Assets Discovered | {briefing['total_assets']} |")
        md.append(f"| High-Risk Perimeter Assets | {briefing['high_risk_count']} |")
        md.append(f"| Subdomain Takeovers Identified | {briefing['takeovers_count']} |")
        md.append(f"| Sensitive Data Leaks (.env, git) | {briefing['leaks_count']} |")
        md.append(f"| Exposed Cloud Storage Buckets | {briefing['buckets_count']} |")
        md.append(f"| Open Ports & Listening Services | {briefing['exposed_services_count']} |")
        md.append(f"| Exploitable Attack Paths Mapped | {briefing['attack_paths_count']} |\n")

        md.append("## 2. Strategic Key Findings\n")
        for finding in briefing["key_findings"]:
            md.append(f"- {finding}")
        md.append("")

        # High risk assets details
        high_risk = [n for n in nodes if n.properties.get("threat_score", 0) >= 60 or n.entity_type in (
            EntityType.TAKEOVER_VULNERABILITY, EntityType.EXPOSURE_LEAK
        )]
        if high_risk:
            md.append("## 3. High-Risk Asset Breakdown\n")
            md.append("| Asset / URN | Type | Threat Score | Critical Finding / Details |")
            md.append("| :--- | :--- | :--- | :--- |")
            for n in high_risk[:25]:
                score = n.properties.get("threat_score", "N/A")
                details = n.properties.get("reason") or n.properties.get("title") or n.properties.get("service") or "High exposure vulnerability"
                md.append(f"| `{n.value}` | `{n.entity_type}` | **{score}** | {details} |")
            md.append("")

        # Attack paths
        if attack_paths:
            md.append("## 4. Exploitable Attack Path Chains\n")
            for i, p in enumerate(attack_paths[:5], 1):
                src = p.get('source_urn') or p.get('start_node') or 'Perimeter'
                tgt = p.get('target_urn') or p.get('target_node') or 'Asset'
                hops = p.get('path_urns') or p.get('path') or [src, tgt]
                score = p.get('total_threat_score') or p.get('average_threat_score') or 0
                md.append(f"### Path #{i} (Score: {score}, Hops: {p.get('hop_count', 0)})\n")
                md.append(f"- **Entry Point:** `{src}`")
                md.append(f"- **Crown Jewel / Target:** `{tgt}`")
                md.append(f"- **Attack Chain:** {' -> '.join(hops)}\n")


        # Infrastructure Clusters
        if clusters:
            md.append("## 5. Discovered Infrastructure Clusters\n")
            md.append("| Cluster ID | Label | Density | Node Count | Top Hub Node |")
            md.append("| :--- | :--- | :--- | :--- | :--- |")
            for c in clusters[:10]:
                md.append(
                    f"| {c['cluster_id']} | {c['label']} | {c['density']} | {c['node_count']} | `{c['hub_node']}` |"
                )
            md.append("")

        md.append("## 6. Actionable Remediation Roadmap\n")
        for i, rec in enumerate(briefing["recommendations"], 1):
            md.append(f"{i}. **[Priority P{i-1}]** {rec}")
        md.append("\n---\n*Report compiled autonomously by Heimdall OSINT Engine.*")

        return "\n".join(md)

    def generate_html(
        self,
        target_name: str,
        nodes: List[GraphNode],
        edges: List[GraphEdge],
        attack_paths: Optional[List[Dict[str, Any]]] = None,
    ) -> str:
        """Generate styled, print-to-PDF ready standalone HTML report."""
        now = datetime.datetime.now(datetime.timezone.utc).strftime("%B %d, %Y %H:%M UTC")
        briefing = self.copilot.generate_executive_briefing(nodes, edges, attack_paths)
        clusters = self.cluster_engine.detect_communities(nodes, edges)

        high_risk = [n for n in nodes if n.properties.get("threat_score", 0) >= 60 or n.entity_type in (
            EntityType.TAKEOVER_VULNERABILITY, EntityType.EXPOSURE_LEAK
        )]

        risk_rows = ""
        for n in high_risk[:30]:
            score = n.properties.get("threat_score", "N/A")
            details = n.properties.get("reason") or n.properties.get("title") or n.properties.get("service") or "High exposure vulnerability"
            risk_rows += f"""
            <tr>
                <td style="font-family: monospace; font-weight: 600; color: #38bdf8;">{n.value}</td>
                <td><span class="badge badge-sub">{n.entity_type}</span></td>
                <td><span class="badge badge-risk">{score}</span></td>
                <td style="color: #cbd5e1;">{details}</td>
            </tr>
            """

        cluster_rows = ""
        for c in clusters[:10]:
            cluster_rows += f"""
            <tr>
                <td>#{c['cluster_id']}</td>
                <td style="font-weight: 600; color: #a78bfa;">{c['label']}</td>
                <td>{c['density']}</td>
                <td>{c['node_count']}</td>
                <td style="font-family: monospace; color: #94a3b8;">{c['hub_node']}</td>
            </tr>
            """

        paths_html = ""
        if attack_paths:
            for i, p in enumerate(attack_paths[:5], 1):
                src = p.get('source_urn') or p.get('start_node') or 'Perimeter'
                tgt = p.get('target_urn') or p.get('target_node') or 'Asset'
                hops = p.get('path_urns') or p.get('path') or [src, tgt]
                score = p.get('total_threat_score') or p.get('average_threat_score') or 0
                chain_hops = " &rarr; ".join([f"<span class='hop'>{hop}</span>" for hop in hops])
                paths_html += f"""
                <div class="path-card">
                    <div style="display: flex; justify-content: space-between; margin-bottom: 8px;">
                        <span style="font-weight: 700; color: #f87171;">Attack Chain #{i}</span>
                        <span style="font-size: 0.85rem; color: #94a3b8;">Threat Score: <strong>{score}</strong> | Hops: <strong>{p.get('hop_count', 0)}</strong></span>
                    </div>
                    <div style="font-size: 0.85rem; line-height: 1.6; margin-bottom: 6px;">
                        <strong>Target:</strong> <span style="color: #facc15;">{tgt}</span>
                    </div>
                    <div style="font-size: 0.8rem; background: #0f172a; padding: 8px 12px; border-radius: 6px; overflow-x: auto; white-space: nowrap;">
                        {chain_hops}
                    </div>
                </div>
                """
        else:
            paths_html = "<p style='color: #64748b;'>No exploitable attack chains detected on analyzed perimeter.</p>"


        findings_html = "".join([f"<li style='margin-bottom: 8px;'>{f}</li>" for f in briefing["key_findings"]])
        recs_html = "".join([f"<li style='margin-bottom: 8px;'><strong>Priority:</strong> {r}</li>" for r in briefing["recommendations"]])

        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Heimdall Threat Intelligence Report - {target_name}</title>
<style>
    :root {{
        --bg: #0b0f19;
        --card-bg: #111827;
        --border: #1f2937;
        --text: #f3f4f6;
        --text-muted: #9ca3af;
        --accent: #3b82f6;
        --danger: #ef4444;
        --warning: #f59e0b;
        --success: #10b981;
    }}
    body {{
        font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
        background-color: var(--bg);
        color: var(--text);
        margin: 0;
        padding: 40px 20px;
        line-height: 1.5;
    }}
    .container {{
        max-width: 1000px;
        margin: 0 auto;
    }}
    .header {{
        display: flex;
        justify-content: space-between;
        align-items: center;
        border-bottom: 1px solid var(--border);
        padding-bottom: 24px;
        margin-bottom: 32px;
    }}
    .title h1 {{
        font-size: 1.8rem;
        margin: 0 0 6px 0;
        letter-spacing: -0.5px;
    }}
    .title p {{
        margin: 0;
        color: var(--text-muted);
        font-size: 0.9rem;
    }}
    .posture-badge {{
        background: {briefing['posture_color']}20;
        border: 1px solid {briefing['posture_color']};
        color: {briefing['posture_color']};
        padding: 10px 20px;
        border-radius: 8px;
        font-weight: 700;
        font-size: 1.1rem;
        text-transform: uppercase;
        letter-spacing: 1px;
    }}
    .metrics-grid {{
        display: grid;
        grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
        gap: 16px;
        margin-bottom: 32px;
    }}
    .metric-card {{
        background: var(--card-bg);
        border: 1px solid var(--border);
        border-radius: 8px;
        padding: 18px;
        text-align: center;
    }}
    .metric-value {{
        font-size: 2rem;
        font-weight: 800;
        color: #fff;
    }}
    .metric-label {{
        font-size: 0.8rem;
        color: var(--text-muted);
        text-transform: uppercase;
        letter-spacing: 0.5px;
        margin-top: 4px;
    }}
    .section {{
        background: var(--card-bg);
        border: 1px solid var(--border);
        border-radius: 8px;
        padding: 24px;
        margin-bottom: 28px;
    }}
    .section h2 {{
        font-size: 1.25rem;
        margin-top: 0;
        margin-bottom: 16px;
        display: flex;
        align-items: center;
        gap: 8px;
        color: #f1f5f9;
        border-bottom: 1px solid var(--border);
        padding-bottom: 12px;
    }}
    table {{
        width: 100%;
        border-collapse: collapse;
        font-size: 0.88rem;
    }}
    th, td {{
        padding: 10px 14px;
        text-align: left;
        border-bottom: 1px solid var(--border);
    }}
    th {{
        background: #0f172a;
        color: var(--text-muted);
        text-transform: uppercase;
        font-size: 0.75rem;
        letter-spacing: 0.5px;
    }}
    .badge {{
        display: inline-block;
        padding: 3px 8px;
        border-radius: 4px;
        font-size: 0.75rem;
        font-weight: 600;
    }}
    .badge-risk {{
        background: #ef444430;
        color: #f87171;
        border: 1px solid #ef4444;
    }}
    .badge-sub {{
        background: #3b82f620;
        color: #60a5fa;
        border: 1px solid #3b82f6;
    }}
    .path-card {{
        background: #0f172a;
        border: 1px solid #334155;
        border-radius: 6px;
        padding: 14px;
        margin-bottom: 12px;
    }}
    .hop {{
        background: #1e293b;
        padding: 2px 6px;
        border-radius: 3px;
        font-family: monospace;
        color: #38bdf8;
    }}
    .print-btn {{
        background: var(--accent);
        color: #fff;
        border: none;
        padding: 8px 16px;
        border-radius: 6px;
        font-weight: 600;
        cursor: pointer;
        font-size: 0.85rem;
    }}
    @media print {{
        body {{ background: #fff; color: #000; padding: 0; }}
        .section, .metric-card {{ border: 1px solid #ccc; background: #fff; }}
        .print-btn {{ display: none; }}
        th {{ background: #eee; color: #000; }}
    }}
</style>
</head>
<body>
<div class="container">
    <div class="header">
        <div class="title">
            <h1>Heimdall Threat Intelligence Report</h1>
            <p>Target: <strong>{target_name}</strong> | Generated: {now}</p>
        </div>
        <div>
            <span class="posture-badge">{briefing['posture_rating']}</span>
            <button class="print-btn" onclick="window.print()" style="margin-left: 12px;">Print / PDF</button>
        </div>
    </div>

    <div class="metrics-grid">
        <div class="metric-card">
            <div class="metric-value" style="color: #38bdf8;">{briefing['total_assets']}</div>
            <div class="metric-label">Total Assets</div>
        </div>
        <div class="metric-card">
            <div class="metric-value" style="color: #f87171;">{briefing['high_risk_count']}</div>
            <div class="metric-label">High Risk</div>
        </div>
        <div class="metric-card">
            <div class="metric-value" style="color: #fb923c;">{briefing['takeovers_count']}</div>
            <div class="metric-label">DNS Takeovers</div>
        </div>
        <div class="metric-card">
            <div class="metric-value" style="color: #facc15;">{briefing['leaks_count']}</div>
            <div class="metric-label">Sensitive Leaks</div>
        </div>
        <div class="metric-card">
            <div class="metric-value" style="color: #a78bfa;">{briefing['buckets_count']}</div>
            <div class="metric-label">Cloud Buckets</div>
        </div>
        <div class="metric-card">
            <div class="metric-value" style="color: #e879f9;">{briefing['attack_paths_count']}</div>
            <div class="metric-label">Attack Chains</div>
        </div>
    </div>

    <div class="section">
        <h2>Strategic Findings & Insights</h2>
        <ul style="padding-left: 20px; line-height: 1.7;">
            {findings_html}
        </ul>
    </div>

    <div class="section">
        <h2>High-Risk Vulnerability & Asset Matrix</h2>
        <table>
            <thead>
                <tr>
                    <th>Asset Name</th>
                    <th>Entity Type</th>
                    <th>Threat Score</th>
                    <th>Evidence / Finding Details</th>
                </tr>
            </thead>
            <tbody>
                {risk_rows if risk_rows else "<tr><td colspan='4' style='text-align:center; color: #64748b;'>No high-risk assets detected.</td></tr>"}
            </tbody>
        </table>
    </div>

    <div class="section">
        <h2>Active Attack Chains & Traversal Paths</h2>
        {paths_html}
    </div>

    <div class="section">
        <h2>Infrastructure Clusters & Graph Communities</h2>
        <table>
            <thead>
                <tr>
                    <th>Cluster</th>
                    <th>Label</th>
                    <th>Density</th>
                    <th>Assets</th>
                    <th>Top Central Hub</th>
                </tr>
            </thead>
            <tbody>
                {cluster_rows if cluster_rows else "<tr><td colspan='5' style='text-align:center; color: #64748b;'>No communities computed.</td></tr>"}
            </tbody>
        </table>
    </div>

    <div class="section">
        <h2>Actionable Remediation Roadmap</h2>
        <ol style="padding-left: 20px; line-height: 1.8;">
            {recs_html}
        </ol>
    </div>

    <div style="text-align: center; color: var(--text-muted); font-size: 0.8rem; margin-top: 40px;">
        Generated by Heimdall OSINT Graph Engine. Confidential Security Assessment.
    </div>
</div>
</body>
</html>
"""
        return html
